### ISSUE TITLE
スマホ表示で狭くなった時に検索ボックスが見づらい

### ISSUE THREAD

**Issue by saki7** [cpprefjp/crsearch#24]
少なくともパンくずの上か下にflexできちんとwrapさせてあげたい

![screenshot_20171029-144623](https://user-images.githubusercontent.com/1901813/32141016-0f395bee-bcb8-11e7-9938-fba885ea539a.png)

**Comment by saki7** [comment]
こっちで必要なのは多分 min-width の設定で、それが無いとホスト側のflexで解釈のしようがない

**Comment by saki7** [comment]
iPhoneを持っていないのでiPhoneの画面が見たい

**Comment by yumetodo** [comment]
iPod touch iOS 11.0.3
![img_7807](https://user-images.githubusercontent.com/10869046/32141357-bd809182-bcc1-11e7-94e9-611a72a71a3e.PNG)
![img_7808](https://user-images.githubusercontent.com/10869046/32141359-bf4821ec-bcc1-11e7-911b-1e7c8b447266.PNG)
![img_7809](https://user-images.githubusercontent.com/10869046/32141361-c0858efa-bcc1-11e7-9af4-f544f5bc0988.PNG)
![img_7810](https://user-images.githubusercontent.com/10869046/32141362-c1b2acfe-bcc1-11e7-9562-e649f4d36c6f.PNG)

**Comment by yumetodo** [comment]
@saki7 
単に

```css
.content-header {
  flex-wrap: wrap
}
.breadcrumb {
  win-width: 350px;
}
.crsearch {
  min-width: 260px;
}
```

を追記するではだめですかね？
